import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { useEffect, useState } from 'react'


export default function Home() {
  const [input, setInput] = useState("")
  const [suggestion, setSuggestion] = useState("")
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(false)

  useEffect(() => {
    if(input.length < 45) setError(false)
  })


  const submit = async () => {
    if (input.length > 45) setError(true)
    setLoading(true)
    try {
      const res = await fetch("/api/marketing-copy", {
        method: "POST",
        headers: {
          'Content-Type': "application/json"
        },
         body: JSON.stringify({ input }),
      })
      const suggestion: { result: string } = await res.json()
      const {result} = suggestion
      setSuggestion(result)
      // console.log(result)
    } catch (error) {
      console.log(error)
    } finally {
      setLoading(false)
    }
  
  }
  return (
    <>
      <Head>
        <title>Marketing Copy Generator 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/a3.jpg" />
      </Head>
      
      <div className='max-w-[550px] mx-auto'>
       <Navbar/>
       <h2 className='text-4xl font-bold text-center my-8'>Marketing <span className="text-teal-500">Copy</span> Generator</h2>
        <div className="flex flex-col gap-4 justify-center w-2/3 mx-auto">

          <div className="w-full relative" >
          {error && (
              <p className="text-xs ml-1 text-red-500 pt-1">Character limt exceeded, please enter less text</p>
            )}
            <textarea 
              value={input}
              onChange={(e) => setInput(e.target.value)}
            rows={3} 
           placeholder="Enter your topic here"
          className="w-full border border-gray-300 bg-white py-2 px-4 rounded-md text-md focus:outline-none resize-none "
            />
            <div className={`absolute ${input.length > 45 ? 'text-red-500': 'text-gray-400'} bottom-2 right-2  text-xs`}>
              <span>{input.length}</span>/45
              </div>
          </div>
          <button className='bg-teal-600 hover:bg-teal-700 font-bold py-2 px-4 rounded-md text-white' type="button" onClick={submit}>
            {loading ? 'Generating...' : "Generate"}
          </button>
          {suggestion && (
          <div className=" mt-8">
            <h4 className='font-semibold pb-2 ml-1'>Here's your <span className='text-teal-500'>marketing</span> Copy:</h4>
          <div className="relative w-full bg-gray-100 p-5 rounded-md">
              <p className='text-md text-gray-700 '>{suggestion}</p>
          </div>
            </div>
          )}
        </div>
        <Footer/>
      </div>
    </>
  )
}
